### ISSUE TITLE
check with specific website like google.com

### ISSUE THREAD

**Issue by Egida** [monosans/proxy-scraper-checker#16]
Hi, can you add this feature?

**Comment by monosans** [comment]
Hi,

I'd like to hear why this feature should exist.

**Comment by AIQubeAI** [comment]
He never answered, but the feature, to check the proxys against specific websites is very useful. For example you need a working proxy for facebook.com. It makes a lot more sense, to check the proxys against facebook.com, because like this you can be 100% sure the checked proxy can resolve facebook.com. A lot of the free proxys available in the internet, can just resolve some "whitelisted" websites. So its possible for a proxy to resolve ip-api.com/json but not facebook.com

**Comment by monosans** [comment]
> He never answered, but the feature, to check the proxys against specific websites is very useful. For example you need a working proxy for facebook.com. It makes a lot more sense, to check the proxys against facebook.com, because like this you can be 100% sure the checked proxy can resolve facebook.com. A lot of the free proxys available in the internet, can just resolve some "whitelisted" websites. So its possible for a proxy to resolve ip-api.com/json but not facebook.com

The problem with checking the proxy on some other site is that it would be impossible to know the geolocation of the proxy and determine if the proxy is anonymous.

**Comment by Egida** [comment]
> He never answered, but the feature, to check the proxys against specific websites is very useful. For example you need a working proxy for facebook.com. It makes a lot more sense, to check the proxys against facebook.com, because like this you can be 100% sure the checked proxy can resolve facebook.com. A lot of the free proxys available in the internet, can just resolve some "whitelisted" websites. So its possible for a proxy to resolve ip-api.com/json but not facebook.com

Didn't answer because it seemed obvious to me

**Comment by AlQubeAl** [comment]
> > He never answered, but the feature, to check the proxys against specific websites is very useful. For example you need a working proxy for facebook.com. It makes a lot more sense, to check the proxys against facebook.com, because like this you can be 100% sure the checked proxy can resolve facebook.com. A lot of the free proxys available in the internet, can just resolve some "whitelisted" websites. So its possible for a proxy to resolve ip-api.com/json but not facebook.com
> 
> The problem with checking the proxy on some other site is that it would be impossible to know the geolocation of the proxy and determine if the proxy is anonymous.

Thats true, but there are two workarounds. Check the geolocation offline against a database for example https://cdn.jsdelivr.net/npm/geolite2-city/

Or first check the custom website, and then against ip-api.com/json

**Comment by monosans** [comment]
> Thats true, but there are two workarounds. Check the geolocation offline against a database for example [cdn.jsdelivr.net/npm/geolite2-city](https://cdn.jsdelivr.net/npm/geolite2-city/)
> 
> Or first check the custom website, and then against ip-api.com/json

This project previously used an offline database with geolocation. But I decided not to do this because these databases did not have information on all IP addresses (about 90%, as I recall). And in addition, every update of that database (which happens once a week) makes me update that database, which makes the `.git` folder start to weigh a lot.

The second approach also has a problem. The script will be slower because it will have to check twice, and besides, as you described above, the proxies may open `facebook.com`, but may not open `ip-api.com/json`.

**Comment by monosans** [comment]
> Thats true, but there are two workarounds. Check the geolocation offline against a database for example [cdn.jsdelivr.net/npm/geolite2-city](https://cdn.jsdelivr.net/npm/geolite2-city/)
> 
> Or first check the custom website, and then against ip-api.com/json

I thought more about the first approach. So every time on startup, the script will download the geolocation database all over again?

**Comment by AlQubeAl** [comment]
> > Thats true, but there are two workarounds. Check the geolocation offline against a database for example [cdn.jsdelivr.net/npm/geolite2-city](https://cdn.jsdelivr.net/npm/geolite2-city/)
> > Or first check the custom website, and then against ip-api.com/json
> 
> I thought more about the first approach. So every time on startup, the script will download the geolocation database all over again?

Yes that would be very nice
